# Generated by Django 3.1.5 on 2021-02-22 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_auto_20210220_1959'),
        ('alerts', '0002_auto_20210221_0309'),
    ]

    operations = [
    ]
