# Generated by Django 3.1.5 on 2021-03-14 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('client_state_previous', models.JSONField(blank=True, editable=False, null=True)),
                ('client_state_updated', models.JSONField(blank=True, editable=False, null=True)),
                ('is_cbr_purpose', models.BooleanField(blank=True, default=False)),
                ('is_disability_referral_purpose', models.BooleanField(blank=True, default=False)),
                ('is_disability_follow_up_purpose', models.BooleanField(blank=True, default=False)),
                ('is_health_provision', models.BooleanField(blank=True, default=False)),
                ('is_education_provision', models.BooleanField(blank=True, default=False)),
                ('is_social_provision', models.BooleanField(blank=True, default=False)),
                ('cbr_worker_name', models.CharField(blank=True, max_length=30)),
                ('location_visit_gps', models.CharField(blank=True, max_length=30)),
                ('location_drop_down', models.CharField(blank=True, max_length=100)),
                ('village_no_visit', models.IntegerField(blank=True, default=0)),
                ('wheelchair_health_provision', models.BooleanField(blank=True, default=False)),
                ('prosthetic_health_provision', models.BooleanField(blank=True, default=False)),
                ('orthotic_health_provision', models.BooleanField(blank=True, default=False)),
                ('repairs_health_provision', models.BooleanField(blank=True, default=False)),
                ('referral_health_provision', models.BooleanField(blank=True, default=False)),
                ('advice_health_provision', models.BooleanField(blank=True, default=False)),
                ('advocacy_health_provision', models.BooleanField(blank=True, default=False)),
                ('encouragement_health_provision', models.BooleanField(blank=True, default=False)),
                ('wheelchair_health_provision_text', models.CharField(blank=True, max_length=100)),
                ('prosthetic_health_provision_text', models.CharField(blank=True, max_length=100)),
                ('orthotic_health_provision_text', models.CharField(blank=True, max_length=100)),
                ('repairs_health_provision_text', models.CharField(blank=True, max_length=100)),
                ('referral_health_provision_text', models.CharField(blank=True, max_length=100)),
                ('advice_health_provision_text', models.CharField(blank=True, max_length=100)),
                ('advocacy_health_provision_text', models.CharField(blank=True, max_length=100)),
                ('encouragement_health_provision_text', models.CharField(blank=True, max_length=100)),
                ('conclusion_health_provision', models.CharField(blank=True, max_length=255)),
                ('advice_education_provision', models.BooleanField(blank=True, default=False)),
                ('advocacy_education_provision', models.BooleanField(blank=True, default=False)),
                ('referral_education_provision', models.BooleanField(blank=True, default=False)),
                ('encouragement_education_provision', models.BooleanField(blank=True, default=False)),
                ('advice_education_provision_text', models.CharField(blank=True, max_length=100)),
                ('advocacy_education_provision_text', models.CharField(blank=True, max_length=100)),
                ('referral_education_provision_text', models.CharField(blank=True, max_length=100)),
                ('encouragement_education_provision_text', models.CharField(blank=True, max_length=100)),
                ('conclusion_education_provision', models.CharField(blank=True, max_length=255)),
                ('advice_social_provision', models.BooleanField(blank=True, default=False)),
                ('advocacy_social_provision', models.BooleanField(blank=True, default=False)),
                ('referral_social_provision', models.BooleanField(blank=True, default=False)),
                ('encouragement_social_provision', models.BooleanField(blank=True, default=False)),
                ('advice_social_provision_text', models.CharField(blank=True, max_length=100)),
                ('advocacy_social_provision_text', models.CharField(blank=True, max_length=100)),
                ('referral_social_provision_text', models.CharField(blank=True, max_length=100)),
                ('encouragement_social_provision_text', models.CharField(blank=True, max_length=100)),
                ('conclusion_social_provision', models.CharField(blank=True, max_length=255)),
                ('client_info_changed', models.JSONField(blank=True, editable=False, null=True)),
                ('additional_notes', models.TextField(blank=True, default='', null=True, verbose_name='additional notes')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('user_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
