# Generated by Django 3.1.5 on 2021-02-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='client_info_changed',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='additional_notes',
            field=models.TextField(blank=True, default='', null=True, verbose_name='additional notes'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='client_state_previous',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='client_state_updated',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
    ]
