# Generated by Django 3.1.5 on 2021-03-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_auto_20210306_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='advice_education_provision_text',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='visit',
            name='advice_health_provision_text',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='visit',
            name='advice_social_provision_text',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='visit',
            name='advocacy_education_provision_text',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='visit',
            name='advocacy_health_provision_text',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='visit',
            name='advocacy_social_provision_text',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='visit',
            name='conclusion_education_provision',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='visit',
            name='conclusion_health_provision',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='visit',
            name='conclusion_social_provision',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='visit',
            name='encouragement_education_provision_text',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='visit',
            name='encouragement_health_provision_text',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='visit',
            name='encouragement_social_provision_text',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='visit',
            name='goal_met_social_provision',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='visit',
            name='orthotic_health_provision_text',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='visit',
            name='prosthetic_health_provision_text',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='visit',
            name='referral_education_provision_text',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='visit',
            name='referral_health_provision_text',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='visit',
            name='referral_social_provision_text',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='visit',
            name='repairs_health_provision_text',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='visit',
            name='wheelchair_health_provision_text',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
