# Generated by Django 3.1.5 on 2021-03-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_auto_20210313_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='location_drop_down',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
