# Generated by Django 3.1.5 on 2021-03-14 01:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0003_auto_20210313_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='datetime_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 3, 14, 1, 1, 17, 442164, tzinfo=utc)),
        ),
    ]
