# Generated by Django 3.1.5 on 2021-04-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0003_auto_20210403_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='visit',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
    ]
