# Generated by Django 3.1.5 on 2021-03-14 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0003_auto_20210314_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='goal_met_education_provision',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='goal_met_health_provision',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='goal_met_social_provision',
        ),
    ]
