# Generated by Django 3.1.5 on 2021-03-14 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0004_auto_20210313_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
