# Generated by Django 3.1.5 on 2021-03-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0004_auto_20210314_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='advice_education_provision_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='visit',
            name='advice_health_provision_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='visit',
            name='advice_social_provision_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='visit',
            name='advocacy_education_provision_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='visit',
            name='advocacy_health_provision_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='visit',
            name='advocacy_social_provision_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='visit',
            name='cbr_worker_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='visit',
            name='conclusion_education_provision',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='visit',
            name='conclusion_health_provision',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='visit',
            name='conclusion_social_provision',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='visit',
            name='encouragement_education_provision_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='visit',
            name='encouragement_health_provision_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='visit',
            name='encouragement_social_provision_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='visit',
            name='location_drop_down',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='visit',
            name='location_visit_gps',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='visit',
            name='orthotic_health_provision_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='visit',
            name='prosthetic_health_provision_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='visit',
            name='referral_education_provision_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='visit',
            name='referral_health_provision_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='visit',
            name='referral_social_provision_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='visit',
            name='repairs_health_provision_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='visit',
            name='wheelchair_health_provision_text',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
