# Generated by Django 3.1.5 on 2021-03-19 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0002_auto_20210314_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaselineSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('general_health', models.CharField(blank=True, choices=[('Very Poor', 'Very Poor'), ('Poor', 'Poor'), ('Fine', 'Fine'), ('GOOD', 'Good')], max_length=50)),
                ('have_access_rehab', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('need_access_rehab', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('assistive_device_have', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('assistive_device_working', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('assistive_device_need', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('assistive_device', models.CharField(blank=True, choices=[('Wheelchair', 'Wheelchair'), ('Prosthetic', 'Prosthetic'), ('Orthotic', 'Orthotic'), ('Crutch', 'Crutch'), ('Walking Stick', 'Walking Stick'), ('Hearing Aid', 'Hearing Aid'), ('Glasses', 'Glasses'), ('Standing Frame', 'Standing Frame'), ('Corner Seat', 'Corner Seat'), ('None', 'None')], default='None', max_length=50)),
                ('health_satisfaction', models.CharField(choices=[('Very Unsatisfied', 'Very Unsatisfied'), ('Unsatisfied', 'Unsatisfied'), ('Satisfied', 'Satisfied'), ('Very Satisfied', 'Very Satisfied')], max_length=50)),
                ('attend_school', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('grade', models.IntegerField(blank=True, default=0)),
                ('reason_no_school', models.CharField(blank=True, choices=[('Lack of Funding', 'Lack Of Funding'), ('My Disability Stops Me', 'Disability Stops'), ('Other', 'Other')], max_length=50)),
                ('been_to_school', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('want_to_go_school', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('feel_valued', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('feel_independent', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('able_to_participate', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('disability_affects_social', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('discriminated', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('working', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('job', models.TextField(blank=True, default='', max_length=50)),
                ('employment', models.CharField(blank=True, choices=[('Employed', 'Employed'), ('Self Employed', 'Self Employed')], max_length=50)),
                ('meets_financial', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('disability_affects_work', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('want_work', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('food_security', models.CharField(blank=True, choices=[('Very Poor', 'Very Poor'), ('Poor', 'Poor'), ('Fine', 'Fine'), ('GOOD', 'Good')], max_length=50)),
                ('enough_food', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('child_nourishment', models.CharField(blank=True, choices=[('Malnourished', 'Malnourished'), ('Undernourished', 'Undernourished'), ('Well Nourished', 'Well Nourished')], max_length=50)),
                ('member_of_organizations', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('aware_of_rights', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('able_to_influence', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('adequate_shelter', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('access_essentials', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('user_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
