# Generated by Django 3.1.5 on 2021-04-10 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_completed', models.DateTimeField(blank=True, null=True)),
                ('client_id', models.IntegerField(blank=True, default=0)),
                ('category', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_initial_goal', models.BooleanField(blank=True, default=False)),
                ('status', models.CharField(max_length=30)),
                ('client_info_changed', models.JSONField(blank=True, editable=False, null=True)),
                ('user_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
