# Generated by Django 3.1.5 on 2021-04-03 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_auto_20210325_0639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='client',
        ),
        migrations.AddField(
            model_name='goal',
            name='client_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='goal',
            name='datetime_completed',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
