# Generated by Django 3.1.5 on 2021-04-03 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_auto_20210403_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='client_state_previous',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='client_state_updated',
        ),
        migrations.AlterField(
            model_name='goal',
            name='datetime_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
