# Generated by Django 3.1.5 on 2021-02-13 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=100)),
                ('gps_location', models.CharField(blank=True, max_length=100)),
                ('consent', models.CharField(max_length=5)),
                ('village_no', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=0)),
                ('contact_client', models.IntegerField(default=0)),
                ('care_present', models.CharField(max_length=5)),
                ('contact_care', models.IntegerField(default=0)),
                ('photo', models.ImageField(default='default.png', upload_to='images/')),
                ('disability', models.CharField(max_length=50)),
                ('health_risk', models.CharField(max_length=30)),
                ('health_require', models.TextField(blank=True)),
                ('health_goal', models.TextField(blank=True)),
                ('education_risk', models.CharField(max_length=30)),
                ('education_require', models.TextField(blank=True)),
                ('education_goal', models.TextField(blank=True)),
                ('social_risk', models.CharField(max_length=30)),
                ('social_require', models.TextField(blank=True)),
                ('social_goal', models.TextField(blank=True)),
                ('risk_score', models.IntegerField(default=0, editable=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
