# Generated by Django 3.1.5 on 2021-02-05 23:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='client',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='care_present',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='consent',
            field=models.CharField(default='Yes', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='contact_care',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_client',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='disability',
            field=models.CharField(default='Amputee', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(default='Male', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='location',
            field=models.CharField(default='BidiBidi Zone 1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='village_no',
            field=models.IntegerField(default=0),
        ),
    ]
