# Generated by Django 3.1.5 on 2021-02-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contact_care',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_client',
            field=models.IntegerField(default=0),
        ),
    ]
