# Generated by Django 3.1.5 on 2021-03-06 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20210305_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contact_care',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_client',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='education_risk',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='health_risk',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='social_risk',
            field=models.IntegerField(default=0),
        ),
    ]
