# Generated by Django 3.1.5 on 2021-04-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20210314_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='care_present',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='client',
            name='consent',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_care',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_client',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='disability',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
