# Generated by Django 3.1.5 on 2021-03-10 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20210306_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientHistoryRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('field', models.CharField(editable=False, max_length=100)),
                ('old_value', models.TextField(editable=False)),
                ('new_value', models.TextField(editable=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', editable=False)),
            ],
        ),
    ]
