# Generated by Django 3.1.5 on 2021-02-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20210215_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='advice_education_provision',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='advice_education_provision_text',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='advice_health_provision',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='advice_health_provision_text',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='advice_social_provision',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='advice_social_provision_text',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='advocacy_education_provision',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='advocacy_education_provision_text',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='advocacy_health_provision',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='advocacy_health_provision_text',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='advocacy_social_provision',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='advocacy_social_provision_text',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='cbr_worker_name',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='client',
            name='conclusion_education_provision',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='conclusion_health_provision',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='conclusion_social_provision',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='encouragement_education_provision',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='encouragement_education_provision_text',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='encouragement_health_provision',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='encouragement_health_provision_text',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='encouragement_social_provision',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='encouragement_social_provision_text',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='goal_met_education_provision',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='client',
            name='goal_met_health_provision',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='client',
            name='goal_met_social_provision',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='is_cbr_purpose',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='is_disability_follow_up_purpose',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='is_disability_referral_purpose',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='is_education_provision',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='is_health_provision',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='is_social_provision',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='location_drop_down',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='client',
            name='location_visit_gps',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='client',
            name='orthotic_health_provision',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='orthotic_health_provision_text',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='prosthetic_health_provision',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='prosthetic_health_provision_text',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='referral_education_provision',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='referral_education_provision_text',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='referral_health_provision',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='referral_health_provision_text',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='referral_social_provision',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='referral_social_provision_text',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='repairs_health_provision',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='repairs_health_provision_text',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='village_no_visit',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='wheelchair_health_provision',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='wheelchair_health_provision_text',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
