# Generated by Django 3.1.5 on 2021-04-07 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_taken_baseline_survey'),
        ('clients', '0003_auto_20210402_2123'),
    ]

    operations = [
    ]
