# Generated by Django 3.1.5 on 2021-03-10 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_clienthistoryrecord'),
        ('clients', '0004_client_cbr_client_id'),
    ]

    operations = [
    ]
