# Generated by Django 3.1.6 on 2021-03-11 06:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_merge_20210310_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cbr_client_id',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
