# Generated by Django 3.1.5 on 2021-04-08 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20210408_0408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='client',
            name='longitude',
        ),
    ]
