# Generated by Django 3.1.5 on 2021-03-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20210310_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_new_client',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
