# Generated by Django 3.1.5 on 2021-03-13 19:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_auto_20210313_0746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='last_modified',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_new_client',
        ),
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='disability',
            field=models.CharField(max_length=250),
        ),
    ]
