# Generated by Django 3.1.5 on 2021-04-11 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_auto_20210410_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
