# Generated by Django 3.1.5 on 2021-03-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_auto_20210314_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='goal_met_education_provision',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='client',
            name='goal_met_health_provision',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='client',
            name='goal_met_social_provision',
            field=models.TextField(blank=True, max_length=30),
        ),
    ]
