# Generated by Django 3.1.6 on 2021-03-14 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_client_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.DateTimeField(blank=True, default=datetime.date(2021, 3, 14)),
        ),
    ]
