# Generated by Django 3.1.6 on 2021-03-14 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_auto_20210314_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
