# Generated by Django 3.1.5 on 2021-03-13 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SyncStatus',
            new_name='Status',
        ),
    ]
