# Generated by Django 3.1.5 on 2021-02-27 22:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='physiotherapyservice',
            old_name='conditions',
            new_name='condition',
        ),
        migrations.RemoveField(
            model_name='physiotherapyservice',
            name='specified_condition',
        ),
        migrations.AddField(
            model_name='physiotherapyservice',
            name='other_description',
            field=models.TextField(blank=True, default='', help_text='Other condition, please specify'),
        ),
        migrations.AddField(
            model_name='referral',
            name='refer_to',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='referral',
            name='service_type',
            field=models.CharField(choices=[('Wheelchair', 'Wheelchair'), ('Physiotherapy', 'Physiotherapy'), ('Prosthetic', 'Prosthetic'), ('Orthotic', 'Orthotic'), ('Other', 'Other')], max_length=50),
        ),
    ]
