# Generated by Django 3.1.5 on 2021-04-11 03:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0002_auto_20210403_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='date_created',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='referral',
            name='outcome',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='referral',
            name='photo',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='status',
            field=models.CharField(default='CREATED', max_length=200),
        ),
    ]
