# Generated by Django 3.1.5 on 2021-04-11 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('referral', '0003_auto_20210410_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='client',
        ),
        migrations.AddField(
            model_name='referral',
            name='client_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='client_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='orthoticservice',
            name='elbow_injury_location',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='otherservice',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='physiotherapyservice',
            name='condition',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='prostheticservice',
            name='knee_injury_location',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='referral',
            name='date_created',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='outcome',
            field=models.TextField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='photo',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='refer_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='service_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='service_object_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='service_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='status',
            field=models.CharField(blank=True, default='CREATED', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='user_creator',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wheelchairservice',
            name='client_has_existing_wheelchair',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='wheelchairservice',
            name='client_hip_width',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='wheelchairservice',
            name='is_wheel_chair_repairable',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='wheelchairservice',
            name='usage_experience',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
