# Generated by Django 3.1.5 on 2021-04-12 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0004_auto_20210411_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='date_created',
        ),
    ]
