# Generated by Django 3.1.5 on 2021-03-29 21:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0002_auto_20210329_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apk',
            name='file',
            field=models.FileField(upload_to='apk/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['apk'])]),
        ),
    ]
